services:
  prefect:
    image: prefecthq/prefect:2-python3.11-conda
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://root:root@postgres:5432/prefect
      - PREFECT_SERVER_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    command: /opt/conda/envs/prefect/bin/prefect server start
    # command: sleep 3600
    networks:
      - q_data_proj_pg_net
  
  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootroot
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - ${MINIO_PATH}:/data:rw

    command: server /data --console-address ":9090"
    networks:
      - q_data_proj_pg_net

  
networks:
  q_data_proj_pg_net: 
    external: True